In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
import re
import warnings
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
#verinin tanımlanması
data = pd.read_excel('/content/sample_data/köklü_veri_seti_zemberek - Kopya.xlsx')
data.head()

label                                           comments
0  mutluluk  gerçek siyaset böyle yap sinir üslup saygı dur...
1  mutluluk  ömür bin yıl ol bık durakla izle barış be yol ...
2  mutluluk            çık konuk ara keyif sıkıl izle bölüm ol
3  mutluluk  bütün mam seri UNK hatta bilgisayar UNK tek bö...
4  mutluluk  bura çık defalarca izle hala doy içten samimi ...

In [ ]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15203 entries, 0 to 15202
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   label     15203 non-null  object
 1   comments  15187 non-null  object
dtypes: object(2)
memory usage: 237.7+ KB


In [ ]:
class_ = Counter(data['label']).keys()
class_

dict_keys(['mutluluk', 'üzüntü', 'korku', 'öfke', 'şaşkınlık'])

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd



# NaN değerleri temizleme
data.dropna(subset=['comments'], inplace=True)

dataDoc = data['comments'].values.tolist()
dataClass = data['label'].values.tolist()



# Eğitim ve test verisi olarak ayırma
x_train, x_test, y_train, y_test = train_test_split(dataDoc, dataClass, test_size=0.3, random_state=42)

# CountVectorizer kullanarak one-hot encoding
count_vectorizer = CountVectorizer(binary=True)
x_train_one_hot = count_vectorizer.fit_transform(x_train)
x_test_one_hot = count_vectorizer.transform(x_test)

print("Number of documents in x_train_one_hot:", x_train_one_hot.shape)
print("Number of documents in x_test_one_hot:", x_test_one_hot.shape)



Number of documents in x_train_one_hot: (10630, 6557)
Number of documents in x_test_one_hot: (4557, 6557)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC, SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression,SGDClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import CategoricalNB
from sklearn.metrics import mean_squared_error
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt


#logistic regresyon
model = OneVsRestClassifier(LogisticRegression(penalty = 'l2', C=1.0))
model.fit(x_train_one_hot, y_train)

print ("Logistic Regression Accuracy={}".format(accuracy_score(y_test, model.predict(x_test_one_hot))))
logisticpred = accuracy_score(y_test, model.predict(x_test_one_hot))
# F score, precision ve recall değerlerini hesaplayalım

f_score = f1_score(y_test, model.predict(x_test_one_hot), average='macro')
precision = precision_score(y_test, model.predict(x_test_one_hot),average='macro')
recall = recall_score(y_test, model.predict(x_test_one_hot), average='macro')
print("F score:", f_score)
print("Precision:", precision)
print("Recall:", recall)


print("   ")

# Naive Bayes
naive_bayes = MultinomialNB()
naive_bayes.fit(x_train_one_hot, y_train)
nb_pred = naive_bayes.predict(x_test_one_hot)

print('Naive Bayes Accuracy: {}'.format(accuracy_score(y_test, nb_pred)))
print("F Score:", f1_score(y_test, nb_pred, average='macro'))
print("Precision:", precision_score(y_test, nb_pred, average='macro'))
print("Recall:", recall_score(y_test, nb_pred, average='macro'))



print(" ")
# Support Vector Machine (SVM)
svm = OneVsRestClassifier(SVC(kernel='linear'))
svm.fit(x_train_one_hot, y_train)
svm_pred = svm.predict(x_test_one_hot)

print('SVM Accuracy: {}'.format(accuracy_score(y_test, svm_pred)))
print("F Score:", f1_score(y_test, svm_pred, average='macro'))
print("Precision:", precision_score(y_test, svm_pred, average='macro'))
print("Recall:", recall_score(y_test, svm_pred, average='macro'))

print(" ")


# Decision Tree
decision_tree = DecisionTreeClassifier()
decision_tree.fit(x_train_one_hot, y_train)
dt_pred = decision_tree.predict(x_test_one_hot)



print('Decision Tree Accuracy: {}'.format(accuracy_score(y_test, dt_pred)))
print("F Score:", f1_score(y_test, dt_pred, average='macro'))
print("Precision:", precision_score(y_test, dt_pred, average='macro'))
print("Recall:", recall_score(y_test, dt_pred, average='macro'))

print(" ")

# Random Forest
random_forest = RandomForestClassifier()
random_forest.fit(x_train_one_hot, y_train)
rf_pred = random_forest.predict(x_test_one_hot)



print('Random Forest Accuracy: {}'.format(accuracy_score(y_test, rf_pred)))
print("F Score:", f1_score(y_test, rf_pred, average='macro'))
print("Precision:", precision_score(y_test, rf_pred, average='macro'))
print("Recall:", recall_score(y_test, rf_pred, average='macro'))



# K-Nearest Neighbors (KNN)
knn = KNeighborsClassifier(n_neighbors = 15)
knn.fit(x_train_one_hot, y_train)
knn_pred = knn.predict(x_test_one_hot)


print('K-Nearest Neighbors Accuracy: {}'.format(accuracy_score(y_test, knn_pred)))
print("F Score:", f1_score(y_test, knn_pred, average='macro'))
print("Precision:", precision_score(y_test, knn_pred, average='macro'))
print("Recall:", recall_score(y_test, knn_pred, average='macro'))

Logistic Regression Accuracy=0.8078141499472017
F score: 0.8051246796220662
Precision: 0.8079329070335846
Recall: 0.8072903413172461
   
Naive Bayes Accuracy: 0.7983104540654699
F Score: 0.7992526201790744
Precision: 0.8088149856020823
Recall: 0.7994998421251671
 
SVM Accuracy: 0.7465681098204857
F Score: 0.7436915454514865
Precision: 0.7480450126988822
Recall: 0.7461591599973221
 
Decision Tree Accuracy: 0.6114044350580782
F Score: 0.6056168754684643
Precision: 0.6110150485155414
Recall: 0.6108892982336742
 
Random Forest Accuracy: 0.7624076029567054
F Score: 0.7546672955198093
Precision: 0.7710339042455031
Recall: 0.7610392745242919
K-Nearest Neighbors Accuracy: 0.21436114044350582
F Score: 0.10972432624969326
Precision: 0.3537012912869273
Recall: 0.211724370870499


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#Training ML classification models

# Naive Bayes
from sklearn.naive_bayes import GaussianNB, MultinomialNB


# MultinomialNB is used in multi-class classification
#clf = Gaussian#NB()
clf = MultinomialNB()


print(clf)

NB=clf.fit(x_train_one_hot,y_train)
prediction=NB.predict(x_test_one_hot)

# Measuring accuracy on Testing Data
from sklearn import metrics
print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))

# Printing the Overall Accuracy of the model
F1_Score=metrics.f1_score(y_test, prediction, average='weighted')
print('Accuracy of the model on Testing Sample Data:', round(F1_Score,2))

# Importing cross validation function from sklearn
from sklearn.model_selection import cross_val_score



MultinomialNB()
              precision    recall  f1-score   support

       korku       0.93      0.90      0.91       917
    mutluluk       0.85      0.82      0.83       910
        öfke       0.85      0.81      0.83       917
      üzüntü       0.77      0.85      0.81       948
   şaşkınlık       0.91      0.92      0.92       865

    accuracy                           0.86      4557
   macro avg       0.86      0.86      0.86      4557
weighted avg       0.86      0.86      0.86      4557

[[822  17  19  39  20]
 [ 17 742  34  85  32]
 [ 19  41 743  94  20]
 [ 15  69  56 805   3]
 [ 12   8  26  24 795]]
Accuracy of the model on Testing Sample Data: 0.86


In [ ]:
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.model_selection import cross_val_score

# Choose hyperparameters (you can tune these)
svm_clf = SVC(kernel='linear', C=1.0)

# Printing all the parameters of SVM
print(svm_clf)

# Creating the model on Training Data
svm_model = svm_clf.fit(x_train_one_hot, y_train)
prediction_svm = svm_model.predict(x_test_one_hot)

# Measuring accuracy on Testing Data
print(metrics.classification_report(y_test, prediction_svm))
print(metrics.confusion_matrix(y_test, prediction_svm))

# Printing the Overall Accuracy of the model
f1_score_svm = metrics.f1_score(y_test, prediction_svm, average='weighted')
print('Accuracy of the SVM model on Testing Sample Data:', round(f1_score_svm, 2))

# Running 10-Fold Cross-validation on the SVM model
# Using the same SVM classifier for cross-validation
accuracy_values_svm = cross_val_score(svm_clf, x_train_one_hot, y_train, cv=10, scoring='f1_weighted')
print('\nAccuracy values for 10-fold Cross Validation:\n', accuracy_values_svm)
print('\nFinal Average Accuracy of the SVM model:', round(accuracy_values_svm.mean(), 2))


SVC(kernel='linear')
              precision    recall  f1-score   support

       korku       0.90      0.92      0.91       917
    mutluluk       0.84      0.85      0.84       910
        öfke       0.84      0.80      0.82       917
      üzüntü       0.79      0.80      0.80       948
   şaşkınlık       0.93      0.94      0.94       865

    accuracy                           0.86      4557
   macro avg       0.86      0.86      0.86      4557
weighted avg       0.86      0.86      0.86      4557

[[842  14  18  28  15]
 [ 23 770  31  64  22]
 [ 23  50 735  92  17]
 [ 31  69  79 761   8]
 [ 14  13   9  15 814]]
Accuracy of the SVM model on Testing Sample Data: 0.86

Accuracy values for 10-fold Cross Validation:
 [0.84229041 0.84443954 0.85871527 0.84203926 0.86505132 0.85343256
 0.85091767 0.85846883 0.86023571 0.84233413]

Final Average Accuracy of the SVM model: 0.85


In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn import metrics
from sklearn.model_selection import cross_val_score

# Choose hyperparameters for MLP
mlp_clf = MLPClassifier(hidden_layer_sizes=(100,), max_iter=100, solver='adam', random_state=1)

# Printing all the parameters of MLP
print(mlp_clf)

# Creating the model on Training Data
mlp_model = mlp_clf.fit(x_train_one_hot, y_train)
prediction_mlp = mlp_model.predict(x_test_one_hot)

# Measuring accuracy on Testing Data
print(metrics.classification_report(y_test, prediction_mlp))
print(metrics.confusion_matrix(y_test, prediction_mlp))

# Printing the Overall Accuracy of the model
f1_score_mlp = metrics.f1_score(y_test, prediction_mlp, average='weighted')
print('Accuracy of the MLP model on Testing Sample Data:', round(f1_score_mlp, 2))


MLPClassifier(max_iter=100, random_state=1)
              precision    recall  f1-score   support

       korku       0.91      0.90      0.90       917
    mutluluk       0.81      0.83      0.82       910
        öfke       0.81      0.77      0.79       917
      üzüntü       0.77      0.76      0.76       948
   şaşkınlık       0.88      0.93      0.90       865

    accuracy                           0.83      4557
   macro avg       0.84      0.84      0.84      4557
weighted avg       0.83      0.83      0.83      4557

[[826  20  26  25  20]
 [ 24 754  39  63  30]
 [ 22  47 706 110  32]
 [ 28  90  87 717  26]
 [ 10  23  14  16 802]]
Accuracy of the MLP model on Testing Sample Data: 0.83


In [ ]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier

# Choose hyperparameters (you can tune these)
clf = RandomForestClassifier(n_estimators=300, max_depth=20, criterion='gini')

# Printing all the parameters of Random Forest
print(clf)

# Creating the model on Training Data
RF_model = clf.fit(x_train_one_hot, y_train)
prediction = RF_model.predict(x_test_one_hot)

# Measuring accuracy on Testing Data
from sklearn import metrics
print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))

# Printing the Overall Accuracy of the model
F1_Score = metrics.f1_score(y_test, prediction, average='weighted')
print('Accuracy of the model on Testing Sample Data:', round(F1_Score, 2))



# Importing cross-validation function from sklearn
from sklearn.model_selection import cross_val_score

# Running 10-Fold Cross-validation on a given algorithm
# Passing full data X and y because the K-fold will split the data and automatically choose train/test
#Accuracy_Values = cross_val_score(RF_model, X, y, cv=10, scoring='f1_weighted')
#print('\nAccuracy values for 10-fold Cross Validation:\n', Accuracy_Values)
#print('\nFinal Average Accuracy of the model:', round(Accuracy_Values.mean(), 2))

RandomForestClassifier(max_depth=20, n_estimators=300)
              precision    recall  f1-score   support

       korku       0.87      0.91      0.89       917
    mutluluk       0.80      0.81      0.81       910
        öfke       0.83      0.72      0.77       917
      üzüntü       0.76      0.80      0.78       948
   şaşkınlık       0.90      0.92      0.91       865

    accuracy                           0.83      4557
   macro avg       0.83      0.83      0.83      4557
weighted avg       0.83      0.83      0.83      4557

[[835  22  20  23  17]
 [ 36 737  33  82  22]
 [ 27  76 663 118  33]
 [ 48  66  59 755  20]
 [ 11  19  23  14 798]]
Accuracy of the model on Testing Sample Data: 0.83


In [ ]:
# Decision Trees
from sklearn import tree
#choose from different tunable hyper parameters
clf = tree.DecisionTreeClassifier(max_depth=20,criterion='gini')

# Printing all the parameters of Decision Trees
print(clf)

# Creating the model on Training Data
DTree=clf.fit(x_train_one_hot,y_train)
prediction=DTree.predict(x_test_one_hot)

# Measuring accuracy on Testing Data
from sklearn import metrics
print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))

# Printing the Overall Accuracy of the model
F1_Score=metrics.f1_score(y_test, prediction, average='weighted')
print('Accuracy of the model on Testing Sample Data:', round(F1_Score,2))



# Importing cross validation function from sklearn
#from sklearn.model_selection import cross_val_score

# Running 10-Fold Cross validation on a given algorithm
# Passing full data X and y because the K-fold will split the data and automatically choose train/test
#Accuracy_Values=cross_val_score(DTree, X , y, cv=10, scoring='f1_weighted')
#print('\nAccuracy values for 10-fold Cross Validation:\n',Accuracy_Values)
#print('\nFinal Average Accuracy of the model:', round(Accuracy_Values.mean(),2))

DecisionTreeClassifier(max_depth=20)
              precision    recall  f1-score   support

       korku       0.97      0.68      0.80       917
    mutluluk       0.88      0.47      0.61       910
        öfke       0.94      0.38      0.54       917
      üzüntü       0.37      0.92      0.53       948
   şaşkınlık       0.95      0.77      0.85       865

    accuracy                           0.64      4557
   macro avg       0.82      0.64      0.66      4557
weighted avg       0.82      0.64      0.66      4557

[[622   5   1 286   3]
 [  3 429   5 462  11]
 [  1  18 344 548   6]
 [ 12  32  15 874  15]
 [  4   3   2 193 663]]
Accuracy of the model on Testing Sample Data: 0.66


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import cross_val_score

# Choose hyperparameters for Logistic Regression
log_reg_clf = LogisticRegression(solver='liblinear')  # 'liblinear' solver is good for small datasets

# Printing all the parameters of Logistic Regression
print(log_reg_clf)

# Creating the model on Training Data
log_reg_model = log_reg_clf.fit(x_train_one_hot, y_train)
prediction_log_reg = log_reg_model.predict(x_test_one_hot)

# Measuring accuracy on Testing Data
print(metrics.classification_report(y_test, prediction_log_reg))
print(metrics.confusion_matrix(y_test, prediction_log_reg))

# Printing the Overall Accuracy of the model
f1_score_log_reg = metrics.f1_score(y_test, prediction_log_reg, average='weighted')
print('Accuracy of the Logistic Regression model on Testing Sample Data:', round(f1_score_log_reg, 2))

# Running 10-Fold Cross-validation on the Logistic Regression model
accuracy_values_log_reg = cross_val_score(log_reg_model, x_train_one_hot, y_train, cv=10, scoring='f1_weighted')
print('\nAccuracy values for 10-fold Cross Validation:\n', accuracy_values_log_reg)
print('\nFinal Average Accuracy of the Logistic Regression model:', round(accuracy_values_log_reg.mean(), 2))


LogisticRegression(solver='liblinear')
              precision    recall  f1-score   support

       korku       0.95      0.93      0.94       917
    mutluluk       0.88      0.87      0.87       910
        öfke       0.85      0.83      0.84       917
      üzüntü       0.80      0.84      0.82       948
   şaşkınlık       0.94      0.95      0.94       865

    accuracy                           0.88      4557
   macro avg       0.88      0.88      0.88      4557
weighted avg       0.88      0.88      0.88      4557

[[849  13  23  19  13]
 [  8 788  39  58  17]
 [  9  24 758 110  16]
 [ 15  63  63 798   9]
 [ 11  11  11  13 819]]
Accuracy of the Logistic Regression model on Testing Sample Data: 0.88

Accuracy values for 10-fold Cross Validation:
 [0.86164581 0.87732014 0.88658322 0.8667416  0.88760655 0.86604157
 0.88121578 0.88387709 0.88383037 0.87603951]

Final Average Accuracy of the Logistic Regression model: 0.88


In [ ]:
# Adaboost
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

# Choosing Decision Tree with 1 level as the weak learner
DTC=DecisionTreeClassifier(max_depth=2)
clf = AdaBoostClassifier(n_estimators=20, base_estimator=DTC ,learning_rate=0.01)

# Printing all the parameters of Adaboost
print(clf)

# Creating the model on Training Data
AB=clf.fit(x_train_one_hot,y_train)
prediction=AB.predict(x_test_one_hot)

# Measuring accuracy on Testing Data
from sklearn import metrics
print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))

# Printing the Overall Accuracy of the model
F1_Score=metrics.f1_score(y_test, prediction, average='weighted')
print('Accuracy of the model on Testing Sample Data:', round(F1_Score,2))

# Importing cross validation function from sklearn
#from sklearn.model_selection import cross_val_score

# Running 10-Fold Cross validation on a given algorithm
# Passing full data X and y because the K-fold will split the data and automatically choose train/test
#Accuracy_Values=cross_val_score(AB, X , y, cv=10, scoring='f1_weighted')
#print('\nAccuracy values for 10-fold Cross Validation:\n',Accuracy_Values)
#print('\nFinal Average Accuracy of the model:', round(Accuracy_Values.mean(),2))

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=2),
                   learning_rate=0.01, n_estimators=20)


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


              precision    recall  f1-score   support

       korku       0.98      0.50      0.66       917
    mutluluk       0.84      0.28      0.43       910
        öfke       0.96      0.34      0.51       917
      üzüntü       0.29      0.94      0.44       948
   şaşkınlık       0.99      0.45      0.62       865

    accuracy                           0.51      4557
   macro avg       0.81      0.50      0.53      4557
weighted avg       0.81      0.51      0.53      4557

[[458   1   1 457   0]
 [  0 259   2 647   2]
 [  1   2 314 599   1]
 [  6  41   9 890   2]
 [  1   4   0 470 390]]
Accuracy of the model on Testing Sample Data: 0.53
